version: "2.7"

rpc:
  listen: "tcp://127.0.0.1:6001"

server:
  command: php ${WORKING_DIR}/artisan temporal-project:server:init

http:
  address: 0.0.0.0:8000
  pool:
    num_workers: 4

temporal:
  address: ${TEMPORAL_CLI_ADDRESS}
  activities:
    command: "php ${WORKING_DIR}/artisan temporal-project:workflow:init"
    num_workers: 4

logs:
  level: debug
  mode: development
