version: "3.8"

services:
  app:
    build: .
    depends_on:
      - temporal
    environment:
      WORKING_DIR: ${WORKING_DIR}
      TEMPORAL_CLI_ADDRESS: ${TEMPORAL_CLI_ADDRESS}
      PHP_IDE_CONFIG: serverName=Docker
    command: [ "/usr/local/bin/rr", "serve", "-c", ".rr.yaml" ]
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/app

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
    ports:
      - "3306:3306"
    volumes:
      - tp_database_data:/var/lib/postgresql/data

  temporal:
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    depends_on:
      - database
    environment:
      DB: postgresql
      DB_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PWD: ${DB_PASSWORD}
      POSTGRES_SEEDS: database
    restart: always
    ports:
      - "7233:7233"
    volumes:
      - tp_dynamic_config_data:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    image: temporalio/admin-tools:${TEMPORAL_VERSION}
    depends_on:
      - temporal
    environment:
      TEMPORAL_CLI_ADDRESS: ${TEMPORAL_CLI_ADDRESS}
    stdin_open: true
    tty: true

  temporal-ui:
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: ${TEMPORAL_CLI_ADDRESS}
      TEMPORAL_CORS_ORIGINS: ${TEMPORAL_CORS_ORIGINS}
    ports:
      - "8080:8080"

volumes:
  tp_dynamic_config_data:
    driver: local
  tp_database_data:
    driver: local

